/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 welcome.gltf 
Author: David Wigforss (https://sketchfab.com/dwigfor)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dog-welcome-c0a3257957de43d2bd396f93e292bb2f
Title: Dog (Welcome)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./dogWelcome/welcome.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geo1_MAT_Animal_Mammal_Dog_Welcome_0.geometry} material={materials.MAT_Animal_Mammal_Dog_Welcome} scale={9} />
    </group>
  )
}

useGLTF.preload('/welcome.gltf')
